name: Ranger-build-workflow
on:  
  push:
    branches: 
      - 'master'
    tags: 
      - 'march-test-2.3.0'
jobs:
  build-Ranger:
    name: Build Ranger 2.3 with Hadoop 3.3.1, HBase 2.4.14, and Hive 4.0.0-alpha-1
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images
    steps:
      - name: Checkout tag release-ranger-2.3.0
        uses: actions/checkout@v3
        with:
          ref: march-test-2.3.0
      - name: check kernel version info  
        run: lsb_release -a && uname -a
      - name: check jdk version 
        run: java -version
      - name: install openjdk-8-jdk
        run: sudo apt-get -y install openjdk-8-jdk
      - name: build release-ranger-2.3.0 
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        #run: mvn -DskipJSTests -DskipTests clean compile package install
        run: mvn -e -X -rf :ranger-hive-plugin compile package -Dmaven.test.skip=true -Drat.skip=true -Dpmd.skip=true -Dfindbugs.skip=true -Dspotbugs.skip=true -Dcheckstyle.skip=true
      - name: check TAR files
        run: sudo find / -name "ranger-*.tar.gz"
      - name: make folder for save assembly files
        run: mkdir ./Ranger-Release-HBase-2.4.14
      - name: move Tarballs to release folder
        run: cp /home/runner/work/ranger/ranger/target/*.tar.gz ./Ranger-Release-HBase-2.4.14/
      - name: move examples Tarballs to release folder
        run: cp /home/runner/work/ranger/ranger/ranger-examples/target/*.tar.gz ./Ranger-Release-HBase-2.4.14/
      - name: check Ranger-Release-HBase-2.4.14 TAR files
        run: ls -al ./Ranger-Release-HBase-2.4.14/
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package_Ranger-Release-HBase-2.4.14
          path: ./Ranger-Release-HBase-2.4.14
  release-project:
    name: Release Project Apache Ranger 2.3
    needs: build-Ranger
    runs-on: ubuntu-20.04
    steps:
      - name: Create Artifact files path
        run: mkdir ./artifacts
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with: 
          name: Package_Ranger-Release-HBase-2.4.14
          path: ./artifacts
      - name: check Download Artifact path 
        run: ls -alh -R ./
      - name: Archive Release Content
        uses: thedoctor0/zip-release@main
        with:
          type: tar
          filename: Package_Ranger-Release-2.3.0-HBase-2.4.14.tar.gz
          path: ./artifacts
          directory: './'
      - name: check Archive files path
        run: ls -alh -R ./
      - name: Create Release
        id: create_ranger_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Ranger-2.3.0-HBase-2.4.14.v${{ github.run_number }}
          release_name: Ranger-Release-2.3.0-HBase-2.4.14.v${{ github.run_number }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_ranger_release.outputs.upload_url }}
          asset_path: ./Package_Ranger-Release-2.3.0-HBase-2.4.14.tar.gz
          asset_name: Package_Ranger-Release-2.3.0-HBase-2.4.14.v${{ github.run_number }}.tar.gz
          asset_content_type: application/gzip
