name: Ranger-build-workflow
on: 
  push:
    branches: [ march-release-ranger-2.3.0 ]
jobs:
  build-hbase:
    runs-on: ubuntu-20.04
    #https://github.com/actions/runner-images
    steps:
      - name: Checkout tag release-ranger-2.3.0
        uses: actions/checkout@v3
        with:
          ref: release-ranger-2.3.0
      - name: check kernel version info  
        run: lsb_release -a && uname -a
      - name: install openjdk-8-jdk
        run: sudo apt-get -y install openjdk-8-jdk
      - name: build hbase-2.4.14 with Hadoop 3.3.1 and build the Tarballs
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run: mvn -DskipJSTests clean compile package install assembly:single


